<script setup lang="ts">
import CTAButton from '@theme/components/Buttons/CTAButton.vue';
import Footer from '@theme/components/Footer.vue';
import HeroAi from '@theme/components/Hero/HeroAi.vue';
import FeaturesCardList from '@theme/components/Features/FeaturesCardList.vue';
import TestimonialCardList from '@theme/components/Testimonials/TestimonialCardList.vue';
import WCUsedBy from '@theme/components/WCUsedByOrgs/WCUsedBy.vue';
import WCHelloWorld from '@theme/components/Examples/WCHelloWorld.vue';
import ProjectsUsingWCCardList from '@theme/components/WCUsedByProjects/ProjectsUsingWCCardList.vue';

defineProps<{
  footerSections: any[];
}>();
</script>

<template>

  <div class="top-section">
    <HeroAi />
  </div>

  <div class="final-section">
    <div class="section">
      <div class="features-small">
        <div class="feature">
          <h2>Improve the quality of your AI-generated code</h2>
          <p>To ensure code generated by your LLM is valid, performant, and satisfies the prompt, you need to be able to actually execute it. The WebContainer API enables this securely, right inside the user's browser tab.</p>
        </div>
        <div class="feature">
          <h2>Provide a better developer experience for your users</h2>
          <p>With WebContainer API you can provide your users a low-latency in-browser code execution environment seamlessly integrated into your AI application so they can get production-ready code faster.</p>
        </div>
        <div class="feature">
          <h2>Avoid infrastructure and security headaches</h2>
          <p>With no virtual machines or network connections to manage, you can ensure untrusted AI-generated code doesn’t pose security risks to you or your end users.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>Leverage the tech <strong>we use<br/> in our own products.</strong></h2>
    <p>WebContainer API already powers production developer experiences from interactive tutorials to full-blown IDEs. With the WebContainer API, you can build a secure and performant coding environment into your AI applications without worrying about provisioning infrastructure.</p>
    <CTAButton href="/guides/quickstart">Get started!</CTAButton>
  </div>

  <Footer :sections="footerSections" />

</template>

<style scoped lang="scss">
@import '@theme/styles/vars.scss';

.top-section {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: -72px;
  padding-top: 224px;
  padding-bottom: 0px;
  // min-height: 100lvh;
  background-attachment: fixed;
  background-image: url('/img/0001-8-2.jpg');
  background-size: cover;
  background-position: center bottom;
  overflow-x: hidden;
  
  :root.dark & {
    background-image: url('/img/0001-8-2-dk-bluedk.jpg');
  }

  @media (max-width: 1024px) {
    padding-top: 160px;
  }

  h3 {
    @media (max-width: 10240px) {
      margin-top: 52px;
    }
  }
}

.features-small {
  max-width:var(--content-max-width);
  display: flex;
  flex-wrap: wrap;
  justify-content: space-around;
  gap: 84px 40px;
  margin: 52px 0;
  padding: 0 52px;
  @media (max-width: 600px) {
    padding: 0;
  }
}

.feature {
  max-width: 30%;
  display: flex;
  flex-direction: column;
  gap: 28px;
  @media (max-width: 1200px) {
    max-width: 416px;
  }
  h2 {
    font-family: Gilroy, var(--vp-font-family-base);
    font-size: 28px;
    line-height: 1.1;
    font-weight: 400;
    color: #000;
    :root.dark & {
      color: #fff;
    }
    strong {
      font-weight: 600;
    }
  }
  p {
    max-width: 416px;
    font-size: 15px;
    line-height: 1.8;
    @media (max-width: 680px) {
      max-width: 84%;
      font-size: 15px;
      line-height: 1.8;
    }
    @media (max-width: 680px) {
      max-width: 100%;
    }
    @media (max-width: 500px) {
      font-size: 14px;
    }
  }
}

.section > h2 {
  margin-bottom: 32px;
  font-family: Gilroy, var(--vp-font-family-base);
  font-size: 52px;
  line-height: 1.1;
  font-weight: 400;
  letter-spacing: -0.5px;
  color: #000;
  :root.dark & {
    color: #fff;
  }
  strong {
    font-weight: 600;
  }
  @media (max-width: 680px) {
    margin-bottom: 40px;
    font-size: 34px;
  }
  @media (max-width: 600px) {
    font-size: 30px;
  }
}

.section > p {
  width: 760px;
  max-width: 100%;
  margin-bottom: 52px;
  font-size: 17px;
  line-height: 1.8;
  @media (max-width: 680px) {
    max-width: 84%;
    font-size: 15px;
    line-height: 1.8;
  }
  @media (max-width: 680px) {
    max-width: 100%;
  }
}

h3 {
  margin-bottom: 48px;
  font-family: 'Gilroy', sans-serif;
  font-size: 28px;
  font-weight: 400;
  line-height: 1.2;
  text-align: center;
  color: #000;
  :root.dark & {
    color: #fff;
  }
  @media (max-width: 680px) {
    font-size: 26px;
  }
}

.section {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
  max-width:var(--content-max-width);
  padding: 0 18px;
  margin: 100px auto 132px;
  text-align: center;
}

.final-section {
  background-attachment: fixed;
  background-image: url('/img/0001-8-2.jpg');
  background-size: cover;
  background-position: center bottom;
  padding: 16px 0;
  :root.dark & {
    background-image: url('/img/0001-8-2-dk-bluedk.jpg');
  }
}

img {
  max-height: 84px;
  margin-block-end: 24px;
  &.light {
    :root.dark & {
      display: none;
    }
  }
  &.dark {
    :root:not(.dark) & {
      display: none;
    }
  }
}

.external-links {
  padding-bottom: 60px;

  :root.dark & {
    background-image: linear-gradient(to top, rgba(0, 0, 0, 0.16), rgba(0, 0, 0, 0) 360px);
  }

  @media (min-width: $bp-medium) {
    padding-top: 20px;
    padding-bottom: 80px;
  }
}
</style>
